config/routes.rb
Ticketee::Application.routes.draw do

  root :to => "projects#index"

  resources :projects

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index

	end

	def show
		@project = Project.find(params[:id])
	end

	def create
		@project = Project.new(params[:project])
		@project.save
		flash[:notice] = "Project has been created."
		redirect_to @project
	end

	def new 
		@project = Project.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= stylesheet_link_tag "application" %>
<html>
<head>
  <title>Ticketee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |key, value| %>

		<div class='flash' id='<%= key %>'>
			<%= value %>
		</div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<div>
<%= form_for(@project) do |f|%>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<%= f.submit "Create Project" %>
<% end %>
</div>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h2> New project</h2>
<%= render 'form' %>

app/views/projects/show.html.erb
<h2><%= @project.name%></h2>